totalNodesChecked = 74

successfulNodes = [
    "http://localhost:26657",
    "http://3.76.85.22:17658",
    "http://104.245.147.213:26657",
    "http://65.21.24.47:26657",
    "http://65.108.127.249:2001",
    "http://65.21.202.61:25005",
    "http://104.245.147.212:26657",
    "http://65.109.91.165:2001",
    "http://162.19.170.233:15457",
    "http://141.94.138.48:26677",
    "http://104.245.147.196:26657",
    "http://104.245.147.204:26657",
    "http://104.245.147.210:26657",
]

unsuccessfulNodes = [
    "http://148.251.177.108:14957",
    "http://65.109.25.113:14957",
    "http://138.201.204.5:43657",
    "http://74.118.136.163:26657",
    "http://65.109.85.225:2011",
    "http://135.181.16.163:26002",
    "http://10.2.212.11:26657",
    "http://43.131.37.70:26657",
    "http://142.132.156.189:26657",
    "http://207.180.219.160:36657",
    "http://5.181.190.114:11657",
    "http://3.12.34.105:26657",
    "http://109.123.242.163:14957",
    "http://5.161.94.187:26657",
    "http://57.128.20.118:29657",
    "http://194.163.159.174:26657",
    "http://167.235.115.119:26657",
    "http://65.109.68.190:13457",
    "http://195.14.6.2:26657",
    "http://65.109.106.242:26657",
    "http://167.172.155.44:26002",
    "http://51.81.208.63:14957",
    "http://51.91.118.140:26657",
    "http://37.120.245.83:26657",
    "http://23.109.158.180:26657",
    "http://185.252.220.89:26657",
    "http://46.4.5.45:14957",
    "http://146.190.161.210:26003",
    "http://65.108.13.110:26657",
    "http://65.109.85.226:2011",
    "http://143.198.45.216:26001",
    "http://80.64.208.139:26657",
    "http://43.157.44.61:26657",
    "http://63.229.234.75:26657",
    "http://208.88.251.50:26657",
    "http://190.2.155.177:26657",
    "http://148.251.133.248:30057",
    "http://142.132.203.60:26657",
    "http://65.108.225.207:26657",
    "http://167.235.180.97:23457",
    "http://95.217.44.105:36657",
    "http://38.109.200.33:26657",
    "http://116.202.238.252:26657",
    "http://65.21.84.110:26657",
    "http://65.21.84.109:26657",
    "http://95.216.96.112:26657",
    "http://85.207.33.77:26657",
    "http://178.239.197.182:26657",
    "http://37.120.245.99:26657",
    "http://2602:2a0::103:26657",
    "http://89.250.150.241:26657",
    "http://2604:a880:4:1d0::4e9:1000:26003",
    "http://2604:a880:cad:d0::8:f001:26001",
    "http://2604:a880:400:d0::171c:a001:26002",
    "http://136.38.55.33:26657",
    "http://65.108.71.202:26657",
    "http://116.202.231.58:13457",
    "http://2602:2a0::111:26657",
    "http://203.135.141.17:26657",
    "http://2602:2a0::102:26657",
    "http://222.106.187.13:40802",
]

